### ISSUE TITLE
全体の新型コロナウイルウイルス感染症についての表記を統一する

### ISSUE THREAD

**Issue by ygkn** [ritscc/soukai-2020-1#131]
とりあえず assign @tatsuya999

**Comment by tatsuya999** [comment]
これはおそらく2回生方針のとこで急にcovid-19が出てきてコロナに統一した方がいいんじゃねってことだったので多分
@thetaleisalsowhite が担当だと思います

**Comment by thetaleisalsowhite** [comment]
失敬。
